const SHEETS={USERS:'Users',PASSES:'QR_Passes',CHECKINS:'Checkins',REDEEMS:'Redeem_Log',WALLET:'Wallet',SESSIONS:'Sessions',AUDIT:'Audit_Log'};
function doPost(e){try{const p=e.parameter||{};const action=p.action;if(!action)throw new Error('Missing action');const publicActions=['login'];let user=null;if(!publicActions.includes(action))user=requireSession_(p.session_token);const map={login:()=>login_(p),ambassadorDashboard:()=>ambassadorDashboard_(user),createPass:()=>createPass_(user,p),lookupPass:()=>lookupPass_(user,p),partialRedeem:()=>partialRedeem_(user,p),checkout:()=>checkout_(user,p),staffRecent:()=>staffRecent_(user),adminDashboard:()=>adminDashboard_(user),createAmbassador:()=>createAmbassador_(user,p)};if(!map[action])throw new Error('Unknown action');return json_({ok:true,data:map[action]()})}catch(err){return json_({ok:false,error:String(err.message||err)})}}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){return SpreadsheetApp.getActive()}
function sh_(name){const s=ss_().getSheetByName(name);if(!s)throw new Error('Missing sheet '+name+'. Run setupSheets() first.');return s}
function rows_(name){const s=sh_(name),v=s.getDataRange().getValues();if(v.length<2)return[];const h=v[0];return v.slice(1).filter(r=>r.some(x=>x!=='' )).map((r,i)=>Object.fromEntries(h.map((k,j)=>[k,r[j]])))}
function append_(name,obj){const s=sh_(name),h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0];s.appendRow(h.map(k=>obj[k]??''))}
function updateById_(name,idField,idValue,patch){const s=sh_(name),v=s.getDataRange().getValues(),h=v[0],idx=h.indexOf(idField);for(let i=1;i<v.length;i++){if(String(v[i][idx])===String(idValue)){Object.entries(patch).forEach(([k,val])=>{const c=h.indexOf(k);if(c>=0)s.getRange(i+1,c+1).setValue(val)});return true}}return false}
function uuid_(prefix){return prefix+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,10).toUpperCase()}
function now_(){return new Date()}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8).map(b=>(b+256)%256).map(b=>b.toString(16).padStart(2,'0')).join('')}
function login_(p){const role=String(p.role||'').toLowerCase(),u=rows_(SHEETS.USERS).find(x=>String(x.username)===String(p.username)&&String(x.role).toLowerCase()===role&&String(x.status||'ACTIVE')==='ACTIVE');if(!u||String(u.password_hash)!==hash_(p.password||''))throw new Error('Invalid login');const token=uuid_('SES');append_(SHEETS.SESSIONS,{session_token:token,user_id:u.user_id,role:u.role,created_at:now_(),expires_at:new Date(Date.now()+1000*60*60*24*7)});return{token,role:u.role,name:u.name,username:u.username,user_id:u.user_id}}
function requireSession_(token){const s=rows_(SHEETS.SESSIONS).find(x=>String(x.session_token)===String(token));if(!s||new Date(s.expires_at)<new Date())throw new Error('Session expired');const u=rows_(SHEETS.USERS).find(x=>String(x.user_id)===String(s.user_id));if(!u)throw new Error('User not found');return u}
function requireRole_(u,roles){if(!roles.includes(String(u.role)))throw new Error('Permission denied')}
function setupSheets(){const defs={Users:['user_id','role','name','username','password_hash','commission_rate','status','created_at'],QR_Passes:['pass_id','pass_ref','qr_token','ambassador_id','type','label','planned_pax','planned_male','planned_female','remark','status','actual_pax','actual_male','actual_female','sales','created_at','closed_at'],Checkins:['checkin_ref','pass_id','ambassador_id','staff_id','pax','male','female','table_no','remark','created_at'],Redeem_Log:['redeem_ref','pass_id','pass_ref','ambassador_id','staff_id','table_no','sales_amount','commission_rate','commission_amount','final_payment','created_at','status'],Wallet:['wallet_txn_id','ambassador_id','redeem_ref','type','amount','created_at'],Sessions:['session_token','user_id','role','created_at','expires_at'],Audit_Log:['audit_id','user_id','action','entity','entity_id','detail','created_at']};Object.entries(defs).forEach(([n,h])=>{let s=ss_().getSheetByName(n);if(!s)s=ss_().insertSheet(n);if(s.getLastRow()===0)s.appendRow(h)});}
function seedDemoUsers(){setupSheets();const s=rows_(SHEETS.USERS);if(!s.find(x=>x.username==='owner'))append_(SHEETS.USERS,{user_id:'USR-ADMIN',role:'admin',name:'Owner',username:'owner',password_hash:hash_('ChangeMe123!'),commission_rate:0,status:'ACTIVE',created_at:now_()});if(!s.find(x=>x.username==='staff1'))append_(SHEETS.USERS,{user_id:'USR-STAFF1',role:'staff',name:'Staff 1',username:'staff1',password_hash:hash_('ChangeMe123!'),commission_rate:0,status:'ACTIVE',created_at:now_()});}
function createAmbassador_(u,p){requireRole_(u,['admin']);if(!p.name||!p.username||!p.password)throw new Error('Missing fields');if(rows_(SHEETS.USERS).some(x=>String(x.username)===String(p.username)))throw new Error('Username exists');append_(SHEETS.USERS,{user_id:uuid_('AMB'),role:'ambassador',name:p.name,username:p.username,password_hash:hash_(p.password),commission_rate:Number(p.commission_rate||0),status:'ACTIVE',created_at:now_()});audit_(u,'CREATE_AMBASSADOR','user',p.username,p.name);return true}
function createPass_(u,p){requireRole_(u,['ambassador']);const type=String(p.type||'INDIVIDUAL').toUpperCase();if(!['INDIVIDUAL','GROUP'].includes(type))throw new Error('Invalid type');const pass_id=uuid_('PASS'),pass_ref='YT-'+(type==='GROUP'?'G':'I')+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,6).toUpperCase(),qr_token=Utilities.getUuid().replace(/-/g,'');const pax=Number(p.planned_pax||1),m=Number(p.planned_male||0),f=Number(p.planned_female||0);if(m+f!==pax)throw new Error('Male + Female must equal Pax');append_(SHEETS.PASSES,{pass_id,pass_ref,qr_token,ambassador_id:u.user_id,type,label:p.label||'',planned_pax:pax,planned_male:m,planned_female:f,remark:p.remark||'',status:'ISSUED',actual_pax:0,actual_male:0,actual_female:0,sales:0,created_at:now_()});audit_(u,'CREATE_PASS','pass',pass_id,pass_ref);return{pass_id,pass_ref,qr_token}}
function passView_(p){const amb=rows_(SHEETS.USERS).find(x=>String(x.user_id)===String(p.ambassador_id));return{...p,ambassador_name:amb?.name||p.ambassador_id}}
function lookupPass_(u,p){requireRole_(u,['staff','admin']);const q=String(p.token_or_ref||'');const pass=rows_(SHEETS.PASSES).find(x=>String(x.qr_token)===q||String(x.pass_ref)===q);if(!pass)throw new Error('Pass not found');if(String(pass.status)==='VOID')throw new Error('Pass is void');return passView_(pass)}
function partialRedeem_(u,p){requireRole_(u,['staff','admin']);return LockService.getScriptLock().tryLock(10000)?partialLocked_(u,p):(()=>{throw new Error('System busy, retry')})()}
function partialLocked_(u,p){try{const pass=rows_(SHEETS.PASSES).find(x=>String(x.pass_id)===String(p.pass_id));if(!pass)throw new Error('Pass not found');if(['PAID','VOID'].includes(String(pass.status)))throw new Error('Pass closed');const pax=Number(p.pax),m=Number(p.male),f=Number(p.female);if(!(pax>0)||m+f!==pax)throw new Error('Invalid pax');const nr={pax:Number(pass.actual_pax||0)+pax,m:Number(pass.actual_male||0)+m,f:Number(pass.actual_female||0)+f};append_(SHEETS.CHECKINS,{checkin_ref:uuid_('CI'),pass_id:pass.pass_id,ambassador_id:pass.ambassador_id,staff_id:u.user_id,pax,male:m,female:f,table_no:p.table_no||'',remark:p.remark||'',created_at:now_()});updateById_(SHEETS.PASSES,'pass_id',pass.pass_id,{actual_pax:nr.pax,actual_male:nr.m,actual_female:nr.f,status:'PARTIAL'});audit_(u,'PARTIAL_REDEEM','pass',pass.pass_id,`${pax} pax`);const updated=rows_(SHEETS.PASSES).find(x=>String(x.pass_id)===String(pass.pass_id));return{pass:passView_(updated)}}finally{LockService.getScriptLock().releaseLock()}}
function checkout_(u,p){requireRole_(u,['staff','admin']);const lock=LockService.getScriptLock();if(!lock.tryLock(10000))throw new Error('System busy, retry');try{const pass=rows_(SHEETS.PASSES).find(x=>String(x.pass_id)===String(p.pass_id));if(!pass)throw new Error('Pass not found');if(['PAID','VOID'].includes(String(pass.status)))throw new Error('Pass closed');const sales=Number(p.sales_amount);if(!(sales>0))throw new Error('Invalid sales');const amb=rows_(SHEETS.USERS).find(x=>String(x.user_id)===String(pass.ambassador_id));if(!amb)throw new Error('Ambassador not found');const rate=Number(amb.commission_rate||0),commission=Math.round(sales*rate)/100;const redeem_ref='YT-RD-'+Utilities.formatDate(now_(),Session.getScriptTimeZone()||'Asia/Kuala_Lumpur','yyMMdd')+'-'+Utilities.getUuid().replace(/-/g,'').slice(0,5).toUpperCase();append_(SHEETS.REDEEMS,{redeem_ref,pass_id:pass.pass_id,pass_ref:pass.pass_ref,ambassador_id:pass.ambassador_id,staff_id:u.user_id,table_no:p.table_no||'',sales_amount:sales,commission_rate:rate,commission_amount:commission,final_payment:String(p.final_payment)==='1'?'YES':'NO',created_at:now_(),status:'CONFIRMED'});append_(SHEETS.WALLET,{wallet_txn_id:uuid_('WLT'),ambassador_id:pass.ambassador_id,redeem_ref,type:'COMMISSION',amount:commission,created_at:now_()});const newSales=Number(pass.sales||0)+sales,newStatus=String(p.final_payment)==='1'?'PAID':'PARTIALLY_PAID';updateById_(SHEETS.PASSES,'pass_id',pass.pass_id,{sales:newSales,status:newStatus,closed_at:newStatus==='PAID'?now_():''});audit_(u,'CHECKOUT','pass',pass.pass_id,`${sales} / ${commission}`);const updated=rows_(SHEETS.PASSES).find(x=>String(x.pass_id)===String(pass.pass_id));return{redeem_ref,commission,pass:passView_(updated)}}finally{lock.releaseLock()}}
function ambassadorDashboard_(u){requireRole_(u,['ambassador']);const passes=rows_(SHEETS.PASSES).filter(x=>String(x.ambassador_id)===String(u.user_id)).map(passView_).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const wallet=rows_(SHEETS.WALLET).filter(x=>String(x.ambassador_id)===String(u.user_id));return{sales:passes.reduce((a,x)=>a+Number(x.sales||0),0),wallet:wallet.reduce((a,x)=>a+Number(x.amount||0),0),issued_count:passes.length,redeemed_count:passes.filter(x=>Number(x.sales||0)>0).length,passes,wallet_history:wallet.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,100)}}
function staffRecent_(u){requireRole_(u,['staff','admin']);return rows_(SHEETS.REDEEMS).filter(x=>String(u.role)==='admin'||String(x.staff_id)===String(u.user_id)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,50)}
function adminDashboard_(u){requireRole_(u,['admin']);const users=rows_(SHEETS.USERS),wallet=rows_(SHEETS.WALLET),redeems=rows_(SHEETS.REDEEMS),checkins=rows_(SHEETS.CHECKINS);const ambassadors=users.filter(x=>String(x.role)==='ambassador').map(a=>({...a,wallet:wallet.filter(w=>String(w.ambassador_id)===String(a.user_id)).reduce((s,w)=>s+Number(w.amount||0),0)}));return{total_sales:redeems.reduce((s,r)=>s+Number(r.sales_amount||0),0),total_commission:redeems.reduce((s,r)=>s+Number(r.commission_amount||0),0),total_pax:checkins.reduce((s,c)=>s+Number(c.pax||0),0),ambassadors,redeems:redeems.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,100).map(r=>({...r,ambassador_name:users.find(x=>String(x.user_id)===String(r.ambassador_id))?.name||r.ambassador_id}))}}
function audit_(u,action,entity,entity_id,detail){append_(SHEETS.AUDIT,{audit_id:uuid_('AUD'),user_id:u.user_id,action,entity,entity_id,detail,created_at:now_()})}
